version: '3'

services:
  namenode:
    image: sevenrats/hadoop-namenode:latest
    container_name: namenode
    volumes:
      - ./config/hadoop/namenode/:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hm-test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ec2-100-25-15-15.compute-1.amazonaws.com
  
  resourcemanager:
    image: sevenrats/hadoop-resourcemanager:latest
    container_name: resourcemanager
#    environment:
#      SERVICE_PRECONDITION: "namenode: datanode:50075"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ec2-100-25-15-15.compute-1.amazonaws.com
    healthcheck:
      disable: true
